//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.Bets = new HashSet<Bet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> TourId { get; set; }
        public int CommandHId { get; set; }
        public int CommandAId { get; set; }
        public Nullable<int> ScoreH { get; set; }
        public Nullable<int> ScoreA { get; set; }
        public bool Played { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual Command CommandH { get; set; }
        public virtual Command CommandA { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
